# Generated by Django 2.2.24 on 2022-07-22 13:26

from django.db import migrations


def fill_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    buildings = Flat.objects.filter(construction_year__gt=2014)
    for building in buildings:
       building.new_building = True
       building.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_field)
    ]



