# Generated by Django 2.2.24 on 2022-07-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20220725_1327'),
        ('property', '0004_auto_20220722_1702'),
    ]

    operations = [
    ]
