# Generated by Django 2.2.24 on 2022-08-12 07:11

from django.db import migrations


def fill_owners(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    flats = Flat.objects.all()
    for flat in flats:
        Owner.objects.get_or_create(
            name=flat.owner,
            pure_number=flat.owner_pure_number,
            phonenumber=flat.owners_phonenumber
        )

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220812_0020'),
    ]

    operations = [
        migrations.RunPython(fill_owners)
    ]
